### ISSUE TITLE
Lista completa dos 30 dias

### ISSUE THREAD

**Issue by phillipesouza** [IzabellaRibeiro/30DiasCSS#1]
hey Izabella,

Você tem uma lista para os dias seguintes? Curti a ideia.

**Comment by izabellaribeiro** [comment]
Oi @phillipesouza, a criadora do desafio posta gradativamente, com o passar dos dias. Segue o link para o repositório dela: https://github.com/MilenaCarecho/30diasDeCSS

**Comment by phillipesouza** [comment]
@IzabellaRibeiro Pensei que havia uma lista predefinida! Valeuzão!
